#数据源配置
spring:
  #排除DruidDataSourceAutoConfigure(取消druid数据源自动注入)
#  autoconfigure:
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        #为默认数据源起一个名字为 master
        master:
          url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        #为从数据源起一个名字为 other
        other:
          url: jdbc:mysql://192.168.5.9:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
