server:
  port: 8081

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.example.scdclient.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    payload: 59669404
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: scd-server
  consumer:
    check: false

spring:
  application:
    name: scd-client
  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.scdclient: debug
    root: info
  path: ./logs

feign:
  client:
    config:
      #全局配置 feign调用日志打印 (none, basic, headers, full)
      default:
        loggerlevel: full
        connectTimeout: 50000
        readTimeout: 50000

ribbon: # 请求连接的超时时间 默认的时间为 1 秒
  ConnectTimeout: 50000
  # 请求处理的超时时间
  ReadTimeout: 50000