server:
  port: 8080
spring:
  application:
    name: prometheus-test #应用名称
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoint:
    health:
      show-details: always  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}