server:
  port: 8080

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.example.scdserver.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    payload: 59669404
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ""

spring:
  application:
    name: scd-server
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
