server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: scd-server
  consumer:
    check: false

spring:
  application:
    name: scd-client
  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.scdclient: debug
    root: info
  path: ./logs

feign:
  client:
    config:
      #全局配置 feign调用日志打印 (none, basic, headers, full)
      default:
        loggerlevel: full
